---

- name: restart prerender
  systemd:
    name: prerender
    state: restarted
    daemon-reload: true
  become: true

- name: restart server
  systemd:
    name: api-server
    state: restarted
    daemon-reload: true
  become: true

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
  become: true

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  become: true

- name: restart postgresql
  systemd:
    name: postgresql
    state: restarted
  become: true
