---

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  become: true

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  become: true

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: true
