---

production:
    hosts:
        new.southernexposure.com:
            stripe_token: "{{ vault_stripe_prod_token }}"
            helcim_token: "{{ vault_helcim_prod_token }}"
            postgrid_api_key: "{{ vault_postgrid_production_key }}"
            client_stripe_env: production
            avatax_status: AvalaraEnabled
            avatax_environment: production
            avatax_license_key: "{{ vault_avatax_production_key }}"
            avatax_account_id: "{{ vault_avatax_production_account_id }}"
            avatax_company_id: "{{ vault_avatax_production_company_id }}"
            avatax_company_code: "{{ vault_avatax_production_company_code }}"
            use_letsencrypt: true
            letsencrypt_domains: "new.southernexposure.com,www.southernexposure.com,southernexposure.com,wwwvps.southernexposure.com"
            db_host: "{{ vault_production_db_host }}"
            db_port: "{{ vault_production_db_port }}"
            db_name: "{{ vault_production_db_name }}"
            db_user: "{{ vault_production_db_user }}"
            db_pass: "{{ vault_production_db_pass }}"
            base_url: "https://southernexposure.com"
            sese_password: "{{ vault_sese_production_password }}"

staging:
    hosts:
        new-staging.southernexposure.com:
            stripe_token: "{{ vault_stripe_test_token }}"
            helcim_token: "{{ vault_helcim_test_token }}"
            postgrid_api_key: "{{ vault_postgrid_staging_key }}"
            client_stripe_env: test
            avatax_environment: sandbox
            avatax_status: AvalaraEnabled
            avatax_license_key: "{{ vault_avatax_sandbox_key }}"
            avatax_account_id: "{{ vault_avatax_sandbox_account_id }}"
            avatax_company_id: "{{ vault_avatax_sandbox_company_id }}"
            avatax_company_code: "{{ vault_avatax_sandbox_company_code }}"
            use_letsencrypt: true
            letsencrypt_domains: "new-staging.southernexposure.com"
            db_host: "{{ vault_staging_db_host }}"
            db_port: "{{ vault_staging_db_port }}"
            db_name: "{{ vault_staging_db_name }}"
            db_user: "{{ vault_staging_db_user }}"
            db_pass: "{{ vault_staging_db_pass }}"
            base_url: "https://new-staging.southernexposure.com"
            sese_password: "{{ vault_sese_password }}"

localtest:
    hosts:
        sese-www-test.acorn:
            stripe_token: "{{ vault_stripe_test_token }}"
            client_stripe_env: test
            avatax_environment: sandbox
            avatax_status: AvalaraTesting
            avatax_license_key: "{{ vault_avatax_sandbox_key }}"
            avatax_account_id: "{{ vault_avatax_sandbox_account_id }}"
            avatax_company_id: "{{ vault_avatax_sandbox_company_id }}"
            avatax_company_code: "{{ vault_avatax_sandbox_company_code }}"
            use_letsencrypt: false
            letsencrypt_domains: ""
            sese_password: "{{ vault_sese_password }}"
