---

production:
    hosts:
        www.southernexposure.com:
            stripe_token: "{{ vault_stripe_prod_token }}"
            avatax_environment: production
            use_letsencrypt: true
            letsencrypt_domains: "www.southernexposure.com,southernexposure.com"

staging:
    hosts:
        staging.southernexposure.com:
            stripe_token: "{{ vault_stripe_test_token }}"
            avatax_environment: sandbox
            use_letsencrypt: true
            letsencrypt_domains: "staging.southernexposure.com"

localtest:
    hosts:
        sese-www-test.acorn:
            stripe_token: "{{ vault_stripe_test_token }}"
            avatax_environment: sandbox
            use_letsencrypt: false
            letsencrypt_domains: ""
