---

- name: Deploy the Website Code using Docker Compose
  hosts: '{{ host | default("localtest") }}'
  any_errors_fatal: true
  tasks:
    - name: Ensure the Source Code Repository is Up to Date
      ansible.builtin.git:
        repo: "{{ code_respository }}"
        version: "{{ commit }}"
        dest: "{{ code_location }}"
        force: true
        accept_hostkey: true
      become: true
      become_user: deploy

    - name: Install the Environment File for the API Server
      ansible.builtin.template:
        dest: "{{ code_location }}/website-env"
        src: roles/webserver/templates/website-env.j2
        mode: '0600'
      become: true
      become_user: deploy
      tags: build

    - name: Docker login to ghcr.io
      community.docker.docker_login:
        registry_url: "https://ghcr.io/v2/"
        username: "{{ ghcr_username }}"
        password: "{{ ghcr_token }}"
        state: present
        reauthorize: true
      become: true
      become_user: deploy

    - name: Docker Compose up
      community.docker.docker_compose_v2:
        project_src: "{{ code_location }}"
        state: present
        wait: true
        wait_timeout: 30
        env_files:
          - website-env
      become: true
      become_user: deploy
      tags: deploy
      notify:
        - Restart prerender container

  handlers:
    - name: Restart prerender container
      community.docker.docker_container:
        name: prerender
        restart: true
      become: true
      become_user: deploy

# vim: set ft=yaml.ansible :
