---

- name: Install certbot snap
  community.general.snap:
    name: certbot
    classic: true
    state: present
  become: true

- name: Prepare certbot binary
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
  become: true

- name: Ensure LetsEncrypt SSL Certificates Have Been Generated
  ansible.builtin.command: certbot certonly --nginx -n --agree-tos -m webmaster@southernexposure.com -d {{ letsencrypt_domains }}
  args:
    creates: "/etc/letsencrypt/live/{{ inventory_hostname }}"
  when: use_letsencrypt
  become: true

- name: Periodically Renew SSL Certificates
  ansible.builtin.cron:
    name: "certbot_renew"
    minute: "0"
    hour: "0"
    day: "*"
    job: "certbot renew --quiet --nginx"
    state: present
  when: use_letsencrypt
  become: true
