---

- name: Install MSMTP
  apt:
    name:
      - ca-certificates
      - msmtp
      - msmtp-mta
      - s-nail
  become: true

- name: Configure MSMTP
  template:
    dest: /etc/msmtprc
    src: msmtprc.j2
    mode: '0660'
    group: mail
  become: true

- name: Ensure MSMTP Logfile Exists
  file:
    path: /var/log/msmtp.log
    mode: '0660'
    group: mail
    state: touch
  become: true

- name: Ensure MSMTP Logfiles Are Rotated
  copy:
    dest: /etc/logrotate.d/msmtp
    src: roles/webserver/files/logrotate_msmtp
  become: true

- name: Configure Email Aliases
  copy:
    dest: /etc/aliases
    content: "default: webmaster@southernexposure.com"
  become: true
