---

- name: Update Package List
  apt:
    update_cache: true
  become: true

- name: Install Basic Utilities
  apt:
    name:
      - acl
      - git
      - htop
      - vim
  become: true

- import_tasks: users.yaml

- import_tasks: emails.yaml

- import_tasks: security.yaml

- import_tasks: database.yaml
