---

- name: Update Package List
  apt:
    update_cache: true
  tags: basic
  become: true

- name: Install Basic Utilities
  apt:
    name:
      - acl
      - git
      - htop
      - iftop
      - iotop
      - vim
      - python-apt
  tags: basic
  become: true

- name: Configure Personal User Accounts
  import_tasks: users.yaml
  tags: users

- name: Configure Email Sending
  import_tasks: emails.yaml
  tags: email

- name: Configure Server Security
  import_tasks: security.yaml
  tags: security

- name: Configure Web Server
  import_tasks: nginx.yaml
  tags: nginx

- name: Configure Certbot
  import_tasks: certbot.yaml
  tags: certbot

- name: Configure Database
  import_tasks: database.yaml
  tags: database.yaml

- name: Configure Website Code
  import_tasks: code.yaml
  tags: code

- name: Configure Prerender Server
  import_tasks: prerender.yaml
  tags: prerender
