---

- name: Update Package List
  apt:
    update_cache: true
  become: true

- name: Install Basic Utilities
  apt:
    name:
      - acl
      - git
      - htop
      - vim
  become: true

- name: Configure Personal User Accounts
  import_tasks: users.yaml
  tags: users

- name: Configure Email Sending
  import_tasks: emails.yaml
  tags: email

- name: Configure Server Security
  import_tasks: security.yaml
  tags: security

- name: Configure Database
  import_tasks: database.yaml
  tags: database.yaml
