---

- name: Update Package List
  ansible.builtin.apt:
    update_cache: true
  tags: basic
  become: true

- name: Install Basic Utilities
  ansible.builtin.apt:
    name:
      - acl
      - git
      - htop
      - iftop
      - iotop
      - vim
  tags: basic
  become: true

- name: Configure Personal User Accounts
  ansible.builtin.import_tasks: users.yaml
  tags: users

- name: Install Docker
  ansible.builtin.import_tasks: docker.yaml
  tags: docker

- name: Configure Server Security
  ansible.builtin.import_tasks: security.yaml
  tags: security

- name: Configure Web Server
  ansible.builtin.import_tasks: nginx.yaml
  tags: nginx

- name: Configure Certbot
  ansible.builtin.import_tasks: certbot.yaml
  tags: certbot

- name: Configure Prerender Server
  ansible.builtin.import_tasks: prerender.yaml
  tags: prerender

- name: Configure Deploy User
  ansible.builtin.import_tasks: deploy.yaml
  tags: deploy
