---

- name: Update Package List
  apt:
    update_cache: true
  become: true

- name: Install Basic Utilities
  apt:
    name:
      - acl
      - git
      - htop
      - vim
  become: true

- import_tasks: users.yaml
  tags: users

- import_tasks: emails.yaml
  tags: email

- import_tasks: security.yaml
  tags: security

- import_tasks: database.yaml
  tags: database.yaml
