---

- name: Run prerender container
  community.docker.docker_container:
    name: prerender
    image: tvanro/prerender-alpine:7.1.0
    state: started
    restart_policy: always
    ports:
      - "5000:3000"
    cpus: 1
    memory: 1G
    env:
      MEMORY_CACHE: "1"
  become: true
