---


# Updates

- name: Install Unattended Upgrades Packages
  ansible.builtin.apt:
    name:
      - apt-listchanges
      - unattended-upgrades
  become: true

- name: Configure Auto Upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: "{{ item }}"
    mode: '0644'
  with_file:
    - auto-upgrades
  become: true

- name: Enable Unattended Upgrade Email Reports
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^(//)?.*?::Mail "'
    line: 'Unattended-Upgrade::Mail "root";'
  become: true

# SSH
- name: Harden SSH Server Configuration
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^#?PermitRootLogin.*$"
      line: "PermitRootLogin no"
    - regexp: "^#?PasswordAuthentication.*$"
      line: "PasswordAuthentication no"
    - regexp: "^#?X11Forwarding.*$"
      line: "X11Forwarding no"
  notify: Restart sshd
  become: true

# Firewall
- name: Allow Outgoing Connections
  community.general.ufw:
    default: allow
    direction: outgoing
  become: true

- name: Block Incoming Connections
  community.general.ufw:
    default: reject
    direction: incoming
  become: true

- name: Allow SSH Connections
  community.general.ufw:
    rule: allow
    direction: in
    name: OpenSSH
  become: true

- name: Allow HTTP(S) Connections
  community.general.ufw:
    rule: allow
    direction: in
    protocol: tcp
    port: "{{ item }}"
  with_items:
    - "80"
    - "443"
  become: true

- name: Ensure Firewall is Enabled
  community.general.ufw:
    state: enabled
  become: true
