---

- name: Install Pavan's Programs
  apt:
    name:
      - zsh
      - fontconfig
  become: true

- name: Add a User for Pavan
  user:
    name: prikhi
    password: "{{ pavans_password }}"
    groups:
      - adm
      - sudo
    append: true
    shell: "/bin/zsh"
  become: true

- name: Copy Pavan's Public SSH Key
  authorized_key:
    user: prikhi
    key: "{{ item }}"
  with_file:
    - public_keys/pavan

- name: Clone Pavan's Dotfiles
  git:
    repo: "https://github.com/prikhi/dotfiles.git"
    accept_hostkey: true
    dest: /home/prikhi/.dotfiles
  become: true
  become_user: prikhi

- name: Update Pavan's Dotfiles
  shell: cd /home/prikhi/.dotfiles && bash install.sh
  become: true
  become_user: prikhi
