---
# Shared

- name: Add a Common User
  ansible.builtin.user:
    name: sese
    uid: 1005
    password: "{{ sese_password }}"
    groups:
      - adm
      - sudo
    append: true
    shell: "/bin/bash"
  become: true

- name: Copy Public SSH Key's for the Common User
  ansible.posix.authorized_key:
    user: sese
    key: "{{ item }}"
  with_file:
    - public_keys/deploy
  become: true
  become_user: sese
